### ISSUE TITLE
In debian don't recognize livestream

### ISSUE THREAD

**Issue by signedbytes** [ohyou/twitch-viewer#1]
Here is the error:
python twitch-viewer.py twitch.tv/foo proxylist.txt
Obtaining the channel...
Obtained the channel
Preparing the processes...
An error has occurred while trying to use livestreamer package. Is it installed? Do you have Python in your PATH variable?
Traceback (most recent call last):
  File "twitch-viewer.py", line 111, in <module>
    prepare_processes()
  File "twitch-viewer.py", line 99, in prepare_processes
    "url": get_url(), "proxy": {
  File "twitch-viewer.py", line 63, in get_url
    url = json.loads(response)['streams']['worst']['url']
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by JABirchall** [comment]
This is because it is trying to run a sub-process of a windows executable which can be downloaded here: http://docs.livestreamer.io/install.html#windows-binaries

I supose you could download the linux bins and change the code on line 54 to run linux bin instead. Hope this helped your issue.

**Comment by ghost** [comment]
so I've tried to change the line to "livestreamer" no-joy, then I've tried the whole path "/usr/local/bin/livestreamer" and still the same. Any ideas?

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
