### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by ghghwwp** [ohyou/twitch-viewer#11]
After numerous attemps I keep getting errors. The error that always shows up " Error has occurred. Is your channel online? Is your channel name correct?" 

Here's what I did.
Downloaded the program. Added proxies.Changed the url to my account in the script. Registered an app on twitch to get ClientID. Copy pasted Client Id into the script. Launched the script but kept getting that error. 

Maybe I got something wrong, so did anyone actually get this to work recently?

**Comment by peacedink** [comment]
Keep "twitch.tv/" in script, when running script run like this "python c:/scriptname.py your_channel_name"

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
