### ISSUE TITLE
Limited to 20 viewers

### ISSUE THREAD

**Issue by acadian42** [ohyou/twitch-viewer#12]
Even using multiple networks, and entirely different proxies, I am limited to 20 viewers. Any idea what this is about?

**Comment by peacedink** [comment]
Same issue here, that must be cuz of kraken api I guess.

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
