### ISSUE TITLE
20 Views limit, willing to pay

### ISSUE THREAD

**Issue by peacedink** [ohyou/twitch-viewer#13]
I use many proxies but all I get is 20 views, any way to bypass that? Willing to pay, comment here or add me on skype "kazlukas" @ohyou @padinko btw I got my own client id, idk if redirect uri matters.

**Comment by malvinarum** [comment]
How could you get it working? I'm getting the error as it mentioned https://github.com/ohyou/twitch-viewer/issues/16

**Comment by padinko** [comment]
i tried 300 free proxies from internet (not very good) and get ~80 viewers.. maybe you have proxies with bad quality or down proxies.. or you dont have a good connection.. you need ~192kbps download speed for 1 proxy

**Comment by peacedink** [comment]
Did you do something with that client id? It doesnt matter if I use 100 or 500 proxies result is exactly 20viewers all the time.

**Comment by padinko** [comment]
so you can try your own client ID.. line 54

**Comment by peacedink** [comment]
I tried, but still limited to 20 viewers.

**Comment by padinko** [comment]
so maybe your proxy list..
have you tried wait a longer time? i can get 80 viewers with free proxy list only from my and neighbour countries.. list with 300 proxies load maybe 20-40 minutes in my tests

**Comment by peacedink** [comment]
I tried to wait an hour and still the same. Used several proxylists even with 2000 proxies, still I get EXACTLY 20 viewers..

**Comment by peacedink** [comment]
Just ran a script with 1k proxies, got EXACTLY 10. http://twitch.tv/testas45

**Comment by interestinginfo** [comment]
You get 80? did you keep the old client ID or did you change it?

**Comment by Oninous** [comment]
I'm interested to know everyone's results. It took some tinkering but I got it working. Only problem is that it does seem to have a limit of 10 for me. I have 210 high speed Proxies in my file so it should be working great. Has anybody been able to get over 10 recently?

**Comment by Oninous** [comment]
I just changed my file to hold 50 Proxies, I didnt realize it makes a viewer for each proxy entry. Still stuck at 10 viewers. Also, where do we get the value for the custom Client ID in the source file? Is it the one from adding a custom app on the website?

**Comment by ghost** [comment]
same issue with max 10 viewers per process

I tried change run that script double times with different client ID, and count of viewers reached  10 - 20
mb its depends on clientid. client id  i generated through admin panel on twitch

**Comment by Nikay19** [comment]
@lukashenka How did you run double clients with different client ID? When I change the client id the script no longer works and asks if the channel name is correct.

**Comment by thisisatotallyrealaccount** [comment]
I'm still hitting a max of 10 users when I launch two different clients with two different Client-ID's and 20+ proxies.

Is the problem perhaps that each individual proxy/fake viewer also needs an oauth token?

Do we need to generate a list of tokens as well as the list of proxies maybe?

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
