### ISSUE TITLE
An error has occurred while trying to get the stream data. Is the channel online? Is the channel name correct?

### ISSUE THREAD

**Issue by malvinarum** [ohyou/twitch-viewer#16]
```
 wolly@ubuntu-1gb-fra1-01:~/twitch-viewer# python2 twitch-viewer.py lpinsight
Obtaining the channel...
Obtained the channel
Preparing the processes...
An error has occurred while trying to get the stream data. Is the channel online? Is the channel name correct?
wolly@ubuntu-1gb-fra1-01:~/twitch-viewer#

```
I'm getting this error even tho the channel is online.
@ohyou

**Comment by padinko** [comment]
do you got twitch oauth authentification?

it's not twitch-viewer issue but livestreamer.. check https://github.com/chrippa/livestreamer/issues/1456

TLDR (copy from this link):
Step 1. Type livestreamer --twitch-oauth-authenticate. Chrome will open and ask you to login to twitch. It will give you a "page does not exist" error.
Step 2. Check the url. It has a section that says access_token=xxxxxxxxxxxxxxxxxxxxxxxx. Copy this string.
Step 3. if you go to %appdata%/roaming/livestreamer
(or wherever your livestreamer config is located)
you can edit the livestreamerrc file in notepad (or whatever config editing tool you prefer)
and add the line:
twitch-oauth-token=(paste token here without parenthesis)

**Comment by malvinarum** [comment]
Well im trying to run this operation on ubuntu terminal :( @padinko

**Comment by padinko** [comment]
so install livestreamer on your PC, do step 1 and 2

step 3 on terminal ( http://docs.livestreamer.io/twitch_oauth.html )

so
and then edit your config file ( http://docs.livestreamer.io/cli.html#cli-livestreamerrc )
$XDG_CONFIG_HOME/livestreamer/config
or
~/.livestreamerrc

add line
twitch-oauth-token=(paste token here without parenthesis)

**Comment by malvinarum** [comment]
Okay now im trying to run it on a windows server. But im stuck below...

> PS C:\python27\twitch> python run.py channelname
> Obtaining the channel...
> Obtained the channel
> Preparing the processes...
> **. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .**
> **. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .**

it keeps going like this @padinko

**Comment by rdvo** [comment]
Is this fixed? Trying to get it working properly

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
