### ISSUE TITLE
channel error

### ISSUE THREAD

**Issue by adryano112** [ohyou/twitch-viewer#18]
C:\Python27>python twitch-viewer.py
Obtaining the channel...
An error has occurred while trying to read arguments. Did you specify the channel?

==================

channel_url = "twitch.tv/bluestreak15"
processes = []

 ==============================

**Comment by malvinarum** [comment]
in the twitch-viewer.py file change channel_url = "twitch.tv/bluestreak15" to channel_url = "twitch.tv/"
and use the command as C:\Python27>python twitch-viewer.py bluestreak15

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
