### ISSUE TITLE
Error Reading Username

### ISSUE THREAD

**Issue by dinosaw** [ohyou/twitch-viewer#2]
Per your documentation, if the user's Twitch channel is `twitch.tv/foo`, then the only argument you pass would be `foo`. However when doing this, I get an error:

```
copy@host:~/twitch-viewer$ python twitch-viewer.py foo
  File "twitch-viewer.py", line 35
    print "An error has occurred while trying to read arguments. Did you specify the channel?"
                                                                                             ^
SyntaxError: invalid syntax
```

I tested this in valid channel / user names. Any ideas?

**Comment by CrazyTypo** [comment]
Do you still have the same issue? If yes, did you update your script with the newer version here? If so, did you try it on a Windows machine to see the difference in output? Could help target the error more specifically.

**Comment by ohyou** [comment]
@dinosaw make sure you are using python 2.x. It is very likely that it expects the following syntax: `print("...")` because that's how it's done in python 3.x

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
