### ISSUE TITLE
BEST API to get most viewers?

### ISSUE THREAD

**Issue by OldmateJoe** [ohyou/twitch-viewer#25]
When generating a API for the script on the twitch website which 'Application Category' should i use for the most viewers per API key?

Choices are:
Game Integration
Website Integration
Application Integration
Browser extension
Broadcast Suite
Chat Bot
Giveaway Tool
Analytics Tool
Other

Cast Your Votes?
OR
Are they all limited to 10 viewers per API Key and i have to run multiple scripts under different API keys?

Please and Thanks.

**Comment by Nikay19** [comment]
How can I change API?

**Comment by mufin695** [comment]
@OldmateJoe Did you ever find an answer for this?

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
