### ISSUE TITLE
Help I'm a noob at this

### ISSUE THREAD

**Issue by hothotgoodies** [ohyou/twitch-viewer#26]
I installed all 3 things it told me to install. However, whey I type in "C:\Python27\Scripts\twitch-viewer.py hothotgoodies", it says:
File "<stdin>", line 1
C:/Python27/Scripts/twitch-viewer.py hothotgoodies
^
SyntaxError: invalid syntax

What am I doing wrong and what am I supposed to be doing?

Thanks in advance for any help!

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
