### ISSUE TITLE
Wont go past 10 Viewers?

### ISSUE THREAD

**Issue by Helpmenowpleaseandthanks** [ohyou/twitch-viewer#27]
I have Generated my own API
Used 2 Accounts to Generate Different API linked to different Twitch Accounts
Used 2 Commands with differnet API using 10  Different Verified Proxies in each script
Used 1 Command on Second PC and VPN and Used other command on First PC on normal IP address

Wont go Past 10 Viewers? Any fix for this?

**Comment by dforcen** [comment]
Same problem, maybe it's because of twitch or the channel

**Comment by Nikay19** [comment]
Yeah same for me, anyone found a solution for that?

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
