### ISSUE TITLE
Won't detect Twitch channel?

### ISSUE THREAD

**Issue by Soraelis** [ohyou/twitch-viewer#30]
Hello,

I've been trying to get the script running, but whenever I put in my channel as "twitch.tv/[channelname]" or "[channelname]" under channel_url, it comes out with the "Did you specify the URL" error every time.

I can't find a fix for this. I've looked through the rest of the issues, and none of the solutions worked.

Please help me. Thanks.

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
