### ISSUE TITLE
An error has occurred while trying to get the stream data.

### ISSUE THREAD

**Issue by grishzakyan** [ohyou/twitch-viewer#31]
C:\Users\grish\Desktop\twitch view>python twitch-viewer.py azllani
Obtaining the channel...
Obtained the channel
Preparing the processes...
An error has occurred while trying to get the stream data. Is the channel online? Is the channel name correct?

The channel is live, what to do?

![image](https://cloud.githubusercontent.com/assets/19871565/26111300/c584fdac-3a65-11e7-9351-4beffa70c53a.png)

**Comment by grishzakyan** [comment]
one more thing. should I have 
channel_url = "azllani"
or
channel_url = "twitch.tv/azllani" 
here

**Comment by micky2171** [comment]
Neither..

You should have it set to, `channel_url = "twitch.tv/"`
and start it using, `python twitch-viewer.py azllani`

**Comment by grishzakyan** [comment]
OH MY GOD! This finally works everyone!!!!

**Comment by mufin695** [comment]
still getting this error... and im using the 

python twitch-viewer.py azllani

**Comment by rdvo** [comment]
@grishzakyan  howd you get this to work? I keep getting that error.

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
