### ISSUE TITLE
How can i fix this?

### ISSUE THREAD

**Issue by danielenicoletti** [ohyou/twitch-viewer#32]
![image](https://cloud.githubusercontent.com/assets/28761891/26165268/a1921efa-3b2f-11e7-8ec2-df939e57cb1e.png)
How can i fix?

**Comment by grishzakyan** [comment]
pip install livestreamer

**Comment by btx78000** [comment]
same problem here 
C:\Users\Admin\twitch-viewer-bot\twitch-viewer>python twitch-viewer.py esl_ptiwiki
Obtaining the channel...
Obtained the channel
Preparing the processes...
An error has occurred while trying to use livestreamer package. Is it installed? Do you have Python in your PATH variable?
Traceback (most recent call last):
  File "twitch-viewer.py", line 115, in <module>
    prepare_processes()
  File "twitch-viewer.py", line 103, in prepare_processes
    "url": get_url(), "proxy": {
  File "twitch-viewer.py", line 67, in get_url
    url = json.loads(response)['streams']['worst']['url']
UnboundLocalError: local variable 'response' referenced before assignment
C:\Users\Admin\twitch-viewer-bot\twitch-viewer>python -m pip install livestreamer
Requirement already satisfied: livestreamer in c:\users\Admin\twitch-viewer-bot\twitch-viewer
Requirement already satisfied: futures in c:\python27\lib\site-packages (from livestreamer)
Requirement already satisfied: singledispatch in c:\python27\lib\site-packages (from livestreamer)
Requirement already satisfied: requests<3.0,>=1.0 in c:\python27\lib\site-packages (from livestreamer)
Requirement already satisfied: six in c:\python27\lib\site-packages (from singledispatch->livestreamer)

C:\Users\Admin\twitch-viewer-bot\twitch-viewer>

**Comment by danielenicoletti** [comment]
I fixed by coping and pasting livestreamer dll and exe in the folder

**Comment by ghost** [comment]
where did you find livestreamer dll and exe ? :|

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
