### ISSUE TITLE
Limited to 10 viewer

### ISSUE THREAD

**Issue by ghost** [ohyou/twitch-viewer#33]
Limited to 10 viewer

**Comment by alladin322** [comment]
Anyone knows what's the issue? Is it twitch api or script?

**Comment by jakecrowley** [comment]
It's odd because twitch limits 10 views per IP, but we're using proxies here, so it shouldn't be limiting.

**Comment by alladin322** [comment]
I run this script, when invite several real people. It still was 10 viewers.

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
