### ISSUE TITLE
Is the code still working?

### ISSUE THREAD

**Issue by Triden** [ohyou/twitch-viewer#34]
2-3 days ago there were updates. Is the code still working?

**Comment by nimiane** [comment]
From my own personal experiences in the last day or so, no. It's not working anymore.

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
