### ISSUE TITLE
Stream says 10 stream list 0

### ISSUE THREAD

**Issue by Nikay19** [ohyou/twitch-viewer#35]
When Im watching my stream I see 10 viewers but when I go to specific game list of streams it shows 0, any idea why?

**Comment by ghost** [comment]
maybe it has not updated

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
