### ISSUE TITLE
Is this still working

### ISSUE THREAD

**Issue by mufin695** [ohyou/twitch-viewer#37]
wondering if this is still working for anyone?

**Comment by jakecrowley** [comment]
no.

**Comment by Crucial1** [comment]
Yes this works

**Comment by jakecrowley** [comment]
How? For me its limited to 10 viewers.

**Comment by mufin695** [comment]
Mine was limited to 10 viewers... but then it just started saying unable to
connect to stream blah blah blah

**Comment by jakecrowley** [comment]
Yes exactly, thats why i said no, but Crucial1 said it worked for him. So i ask how?

**Comment by Crucial1** [comment]
when first downloaded with latest version python it threw a bunch of error messages which was fixed with quick google search, after that just follow instructions and get free proxies from decent websites

**Comment by mufin695** [comment]
Yeah i had it working fine.. maybe it's my proxy list I'll give it a shot

**Comment by Crucial1** [comment]
if you have errors post them here, i will try and help :)
also looking for @ohyou

**Comment by jakecrowley** [comment]
@Crucial1 Mine throws no errors, but just gets stuck at 10 viewers. I've tried multiple different proxy lists. How many viewers does yours get?

**Comment by Crucial1** [comment]
mine to only gets 10

**Comment by mufin695** [comment]
Obtaining the channel...
Obtained the channel
Preparing the processes...
An error has occurred while trying to get the stream data. Is the channel
online? Is the channel name correct?

the channel is online at the proxy list is up to date

**Comment by mufin695** [comment]
still no luck with this....

**Comment by addlikes** [comment]
mine says that cant find the proxylist file, but the file is in script folder and the name is right, anyone know how to solve this?

**Comment by dankmem** [comment]
I tried modify the python script to use random Client-ID from an array of about 5 or so to see i can go over 10 viewers and it does not. I am using freshly scraped elite/anonymous proxies (not transparent proxies) aswell

**Comment by eirikhr** [comment]
I am having the same issues. I'm wondering if Twitch has found a method to detect these request and puts it on a limiter.

Can't seem to find any other working scripts either.

**Comment by Astriz** [comment]
it doesnt work anymore , not even for 10 , i think we need a new script.

**Comment by mufin695** [comment]
I think you're right Astriz

**Comment by Astriz** [comment]
Maybe we should make something around "streamlink" instead of "livestreamer"

**Comment by mufin695** [comment]
could probably be done

**Comment by gilajila** [comment]
Couldn't even figure how to start it ... Not a tech savvy, Anyone willing to help? I'll pay

**Comment by mufin695** [comment]
@gilajila doesn't work don't even bother....

**Comment by Astriz** [comment]
i fixed abit for 10 again now it doesnt work again...

**Comment by ghost** [comment]
How do I fix this ??? ( Windows 10 )

Cannot open c:\Python27\livestreamer-script.py
An error has occurred while trying to get the stream data. Is the channel online? Is the channel name correct? 


`python C:\Users\myname\Desktop\twitch-viewer-master\twitch-viewer.py mychannel`

**Comment by mufin695** [comment]
Yeah doesn't work anymore...

**Comment by rdvo** [comment]
No support here for this at alL? SAd

**Comment by mufin695** [comment]
It doesn’t work anymore bud. How’s that for support

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
