### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by alamarca** [ohyou/twitch-viewer#38]
C:\Users\steam\Downloads\twitch-viewer-master\twitch-viewer-master>python twitch
-viewer.py masterlatinleague
Obtaining the channel...
Obtained the channel
Preparing the processes...
An error has occurred while trying to use livestreamer package. Is it installed?
 Do you have Python in your PATH variable?
Traceback (most recent call last):
  File "twitch-viewer.py", line 112, in <module>
    prepare_processes()
  File "twitch-viewer.py", line 100, in prepare_processes
    "url": get_url(), "proxy": {
  File "twitch-viewer.py", line 64, in get_url
    url = json.loads(response)['streams']['worst']['url']
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
