### ISSUE TITLE
Erorr

### ISSUE THREAD

**Issue by Joeqa** [ohyou/twitch-viewer#4]
C:>C:\Python27\python.exe C:\twitch-viewer.py naragasu
Obtaining the channel...
Obtained the channel
Preparing the processes...
An error has occurred while trying to get the stream data. Is the channel online
? Is the channel name correct?

**Comment by Joeqa** [comment]
Problem with 

### # Decoding the url to the worst quality of the stream

**Comment by ohyou** [comment]
Should be fixed with the latest update. If it won't, create a new issue please.
