### ISSUE TITLE
Did anyone actually got it to get results?

### ISSUE THREAD

**Issue by CrazyTypo** [ohyou/twitch-viewer#7]
I tried it with 50 working proxies and it does not increase the number of viewers. I waited 35 minutes. the proxies are fully functional as I used it on another software that increases twitch views and it worked.

**Comment by HellBz** [comment]
Me to no change of views, what you use for a programme for test

**Comment by CrazyTypo** [comment]
I used twitch god from babatools.com and it worked. But this program is not generating viewers, at least for me... You know what might be the problem?

**Comment by Asexual** [comment]
I would have you take a look here ideally and replace the current client-id with your own.
https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843#.520ttl1oi

**The ID you need to replace is presented on line 54**

**Comment by CrazyTypo** [comment]
So I need to replace that ID with my own. But what application do I choose the ID from? I create a custom one? if so, how do I create the custom one, it doesn't matter what the settings are as long as I have a client ID? Sorry I'm not very good at these things

**Comment by Maras0830** [comment]
the viewers number was increased just few seconds...

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
