### ISSUE TITLE
API Fix Not Working

### ISSUE THREAD

**Issue by ghost** [ohyou/twitch-viewer#8]
I downloaded the latest script update, and have got everything setup. I am continuously getting this error though and have not found a way to fix it. I read a few troubleshooting pages about this issue, and it looks like you had tried to recently fix it with the new API client ID, but it just will not work for me. Any suggestions? Has this been broken by twitch again?

"An error has occurred while trying to get the stream data. Is the channel online? Is the channel name correct?"

**Comment by ghost** [comment]
Does anybody have any insight on this issue?

**Comment by maxerbox** [comment]
how do you launch the script ?
do you type "python twitch-viewer.py {yourchannel}"

**Comment by Maras0830** [comment]
use  "python twitch-viewer.py /{channelname}"


can work, but it also can not insert viewers.

**Comment by ghost** [comment]
Fixed. Previous contributor failed with the fields.

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
